// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { EffectKind } from "./EffectKind";

export type AddEffectParams = { track_index: number, kind: EffectKind, start: number, end: number, blend_mode: BlendMode, opacity: number, };
