// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionSummary } from "./SectionSummary";

/**
 * Typed return for GetAnalysisSummary.
 */
export type AnalysisSummary = { tempo: number | null, time_signature: number | null, beat_count: number | null, key: string | null, key_confidence: number | null, valence: number | null, arousal: number | null, danceability: number | null, genres: { [key in string]: number } | null, sections: Array<SectionSummary> | null, };
