// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured error type for the application. Replaces stringly-typed errors
 * so the frontend can match on error codes and display appropriate UI.
 */
export type AppError = { "code": "NotFound", "detail": { what: string, } } | { "code": "InvalidIndex", "detail": { what: string, index: number, } } | { "code": "ValidationError", "detail": { message: string, } } | { "code": "IoError", "detail": { message: string, } } | { "code": "NoProfile" } | { "code": "NoSequence" } | { "code": "NoSettings" } | { "code": "ApiError", "detail": { message: string, } } | { "code": "ImportError", "detail": { message: string, } };
