// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Application-level settings stored in the OS config directory.
 */
export type AppSettings = { version: number, data_dir: string, last_profile: string | null, claude_api_key: string | null, };
