// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisFeatures } from "./AnalysisFeatures";
import type { ChatMode } from "./ChatMode";
import type { LlmProviderConfig } from "./LlmProviderConfig";

/**
 * Application-level settings stored in the OS config directory.
 */
export type AppSettings = { version: number, data_dir: string, last_profile: string | null, llm: LlmProviderConfig, 
/**
 * Whether to attempt GPU acceleration for audio analysis (requires NVIDIA CUDA).
 */
use_gpu: boolean, 
/**
 * Default features to run when analyzing audio. None = all enabled.
 */
default_analysis_features: AnalysisFeatures | null, 
/**
 * Chat mode: Basic (direct API calls) or Agent (Claude Agent SDK sidecar).
 */
chat_mode: ChatMode, };
