// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisFeatures } from "./AnalysisFeatures";
import type { BeatAnalysis } from "./BeatAnalysis";
import type { DrumAnalysis } from "./DrumAnalysis";
import type { HarmonyAnalysis } from "./HarmonyAnalysis";
import type { LowLevelFeatures } from "./LowLevelFeatures";
import type { LyricsAnalysis } from "./LyricsAnalysis";
import type { MoodAnalysis } from "./MoodAnalysis";
import type { PitchAnalysis } from "./PitchAnalysis";
import type { StemAnalysis } from "./StemAnalysis";
import type { StructureAnalysis } from "./StructureAnalysis";
import type { VocalPresence } from "./VocalPresence";

/**
 * Complete audio analysis results. Each field is optional so analysis
 * can be run incrementally (e.g., beats only, or stems + lyrics).
 */
export type AudioAnalysis = { 
/**
 * Which features were successfully analyzed
 */
features: AnalysisFeatures, beats: BeatAnalysis | null, structure: StructureAnalysis | null, stems: StemAnalysis | null, lyrics: LyricsAnalysis | null, mood: MoodAnalysis | null, harmony: HarmonyAnalysis | null, low_level: LowLevelFeatures | null, pitch: PitchAnalysis | null, drums: DrumAnalysis | null, vocal_presence: VocalPresence | null, };
