// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddEffectParams } from "./AddEffectParams";
import type { AddTrackParams } from "./AddTrackParams";
import type { DeleteEffectsParams } from "./DeleteEffectsParams";
import type { DeleteTrackParams } from "./DeleteTrackParams";
import type { MoveEffectToTrackParams } from "./MoveEffectToTrackParams";
import type { UpdateEffectParamParams } from "./UpdateEffectParamParams";
import type { UpdateEffectTimeRangeParams } from "./UpdateEffectTimeRangeParams";
import type { UpdateSequenceSettingsParams } from "./UpdateSequenceSettingsParams";
import type { WriteScriptParams } from "./WriteScriptParams";

/**
 * A single action within a batch edit operation.
 * Typed union — adding a variant without handling it is a compiler error.
 */
export type BatchAction = { "action": "add_effect", "params": AddEffectParams } | { "action": "delete_effects", "params": DeleteEffectsParams } | { "action": "update_effect_param", "params": UpdateEffectParamParams } | { "action": "update_effect_time_range", "params": UpdateEffectTimeRangeParams } | { "action": "add_track", "params": AddTrackParams } | { "action": "delete_track", "params": DeleteTrackParams } | { "action": "move_effect_to_track", "params": MoveEffectToTrackParams } | { "action": "update_sequence_settings", "params": UpdateSequenceSettingsParams } | { "action": "write_script", "params": WriteScriptParams };
