// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchAction } from "./BatchAction";

export type BatchEditParams = { description: string, commands: Array<BatchAction>, };
