// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed return for GetBeatsInRange.
 */
export type BeatsInRange = { beats: Array<number>, downbeats: Array<number>, count: number, tempo: number, };
