// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BeatAnalysis = { 
/**
 * Beat times in seconds
 */
beats: Array<number>, 
/**
 * Downbeat times in seconds (first beat of each measure)
 */
downbeats: Array<number>, 
/**
 * Estimated tempo in BPM
 */
tempo: number, 
/**
 * Time signature numerator (e.g., 4 for 4/4)
 */
time_signature: number, 
/**
 * Per-beat confidence values (0.0 - 1.0)
 */
beat_confidences: Array<number>, 
/**
 * Overall tempo confidence (0.0 - 1.0)
 */
tempo_confidence: number, };
