// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How multiple effect layers combine their output.
 */
export type BlendMode = "Override" | "Add" | "Multiply" | "Max" | "Alpha" | "Subtract" | "Min" | "Average" | "Screen" | "Mask" | "IntensityOverlay";
