// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Physical bulb shape, affects display size in the preview renderer.
 */
export type BulbShape = "LED" | "C9" | "C7" | "Mini" | "Flood" | "Icicle" | "Globe" | "Snowflake";
