// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Channel byte ordering within a pixel. Different protocols/chips use different orders.
 * WS2811 defaults to GRB, WS2812 uses GRB, SK6812 uses GRBW, etc.
 */
export type ChannelOrder = "Rgb" | "Grb" | "Brg" | "Rbg" | "Gbr" | "Bgr";
