// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chat mode: Basic (direct API) or Agent (Claude Agent SDK sidecar).
 */
export type ChatMode = "Basic" | "Agent";
