// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chat message role. Serializes to lowercase strings matching the Claude API.
 */
export type ChatRole = "user" | "assistant" | "tool";
