// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChordEvent = { 
/**
 * Chord label (e.g., "Cmaj", "Am7", "N" for no chord)
 */
label: string, 
/**
 * Start time in seconds
 */
start: number, 
/**
 * End time in seconds
 */
end: number, };
