// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a fixture's channels map to color data.
 * Extensible to cover all common LED and conventional fixture types.
 */
export type ColorModel = "Single" | "Rgb" | "Rgbw";
