// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How gradient colors are applied across time/space.
 */
export type ColorMode = "static" | "gradient_per_pulse" | "gradient_through_effect" | "gradient_across_items";
