// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

/**
 * A color stop at a position along the gradient [0, 1].
 */
export type ColorStop = { position: number, color: Color, };
