// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RGBA color with 8-bit channels. Alpha is used for blending during composition.
 */
export type Color = { r: number, g: number, b: number, a: number, };
