// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorStop } from "./ColorStop";

/**
 * A color gradient defined by stops with linear RGB interpolation.
 * Stops are always sorted by position.
 */
export type ColorGradient = { stops: Array<ColorStop>, };
