// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandResult } from "./CommandResult";

/**
 * Full typed response from command execution. Includes the human-readable
 * `message`, the typed `result` (discriminated union the sidecar can narrow),
 * and an optional `data_file` path for large payloads.
 *
 * Exported via ts-rs so the sidecar imports the generated type — no manual
 * mirroring, no drift.
 */
export type CommandResponse = { message: string, result: CommandResult, data_file: string | null, };
