// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of executing a Command. Dual output serves both audiences:
 * LLM/CLI gets `message`, frontend/API gets `data`.
 */
export type CommandOutput = { message: string, data: any, };
