// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandCategory = "Edit" | "Playback" | "Query" | "Analysis" | "Library" | "Script" | "Settings" | "Profile" | "Sequence" | "Media" | "Chat" | "Import";
