// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a controller communicates with the sequencer.
 */
export type ControllerProtocol = { "E131": { unicast_address: string | null, } } | { "ArtNet": { address: string | null, } } | { "Serial": { port: string, baud_rate: number, } };
