// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControllerId } from "./ControllerId";
import type { ControllerProtocol } from "./ControllerProtocol";

/**
 * A physical controller that drives one or more outputs.
 * Examples: Falcon F16V4, ESPixelStick, Kulp K32, etc.
 */
export type Controller = { id: ControllerId, name: string, protocol: ControllerProtocol, };
