// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary returned to the frontend for listing conversations.
 */
export type ConversationSummary = { id: string, title: string, created_at: string, message_count: number, is_active: boolean, };
