// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurvePoint } from "./CurvePoint";

/**
 * Piecewise-linear curve mapping time (x) to value (y), both normalized [0, 1].
 * Points are always sorted by x. Evaluate via binary search + linear interpolation.
 */
export type Curve = { points: Array<CurvePoint>, };
