// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectTarget } from "./EffectTarget";

export type DeleteEffectsParams = { 
/**
 * Array of effect targets to delete.
 */
targets: Array<EffectTarget>, };
