// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectLocation } from "./EffectLocation";

export type DeleteEffectsParams = { 
/**
 * Array of effect locations to delete.
 */
targets: Array<EffectLocation>, };
