// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DMX channel address within a universe. Valid range: 1..=512.
 */
export type DmxAddress = number;
