// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DrumAnalysis = { 
/**
 * Onset times in seconds
 */
onsets: Array<number>, 
/**
 * Onset strengths (0.0 - 1.0), parallel to `onsets`
 */
strengths: Array<number>, };
