// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Easing function for interpolation between keyframes.
 *
 * Standard easing curves following CSS/web animation conventions.
 * `evaluate(t)` maps normalized input [0,1] to eased output.
 */
export type EasingFunction = "hold" | "linear" | "ease_in" | "ease_out" | "ease_in_out" | "ease_in_cubic" | "ease_out_cubic" | "ease_in_out_cubic" | "ease_in_quart" | "ease_out_quart" | "ease_in_out_quart" | "ease_in_sine" | "ease_out_sine" | "ease_in_out_sine" | "ease_in_expo" | "ease_out_expo" | "ease_in_out_expo" | "ease_in_back" | "ease_out_back" | "ease_in_out_back" | "ease_in_elastic" | "ease_out_elastic" | "ease_in_out_elastic" | "ease_in_circ" | "ease_out_circ" | "ease_in_out_circ" | "ease_in_bounce" | "ease_out_bounce" | "ease_in_out_bounce";
