// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKey } from "./ParamKey";
import type { ParamValue } from "./ParamValue";

/**
 * Named, typed parameters for an effect instance.
 * Serializes as a flat JSON object (transparent over the inner HashMap).
 */
export type EffectParams = { [key in ParamKey]?: ParamValue };
