// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which built-in effect type an instance uses.
 * Future: this will be extended with Custom(String) for user-defined effects.
 */
export type EffectKind = "Solid" | "Chase" | "Rainbow" | "Strobe" | "Gradient" | "Twinkle" | "Fade" | "Wipe";
