// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { EffectKind } from "./EffectKind";
import type { EffectParams } from "./EffectParams";
import type { ParamSchema } from "./ParamSchema";
import type { TimeRange } from "./TimeRange";

export type EffectDetail = { kind: EffectKind, schema: Array<ParamSchema>, params: EffectParams, time_range: TimeRange, track_name: string, blend_mode: BlendMode, opacity: number, };
