// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which effect type an instance uses.
 * Built-in effects are enum variants; DSL scripts use `Script(name)`.
 */
export type EffectKind = "Solid" | "Chase" | "Rainbow" | "Strobe" | "Gradient" | "Twinkle" | "Fade" | "Wipe" | { "Script": string };
