// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixtureId } from "./FixtureId";
import type { GroupId } from "./GroupId";

/**
 * What an effect targets: a specific set of fixtures or a named group.
 */
export type EffectTarget = { "Group": GroupId } | { "Fixtures": Array<FixtureId> } | "All";
