// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamValue } from "./ParamValue";

/**
 * A parameter in an effect catalog entry.
 */
export type EffectCatalogParam = { key: string, label: string, type: string, default: ParamValue | null, };
