// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { EffectKind } from "./EffectKind";
import type { EffectParams } from "./EffectParams";
import type { TimeRange } from "./TimeRange";

/**
 * A placed effect on the timeline. Fully describes what happens, when, and to what.
 */
export type EffectInstance = { kind: EffectKind, params: EffectParams, time_range: TimeRange, blend_mode: BlendMode, 
/**
 * Opacity multiplier (0.0 = transparent, 1.0 = fully opaque).
 */
opacity: number, };
