// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectCatalogParam } from "./EffectCatalogParam";

/**
 * A single entry in the effect catalog.
 */
export type EffectCatalogEntry = { kind: string, name: string, type: string, params: Array<EffectCatalogParam> | null, };
