// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a field update that distinguishes "absent" from "null" from "value".
 * Use as `Option<FieldUpdate<T>>` with `#[serde(default, deserialize_with = "field_update_opt::deserialize")]`.
 *
 * - `None` (field absent via `#[serde(default)]`) → skip / unchanged
 * - `Some(FieldUpdate::Clear)` (JSON `null`) → clear the field
 * - `Some(FieldUpdate::Set(v))` (JSON value) → set the field
 */
export type FieldUpdate<T> = null | T;
