// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixtureId } from "./FixtureId";
import type { LayoutShape } from "./LayoutShape";
import type { Position2D } from "./Position2D";

/**
 * Maps a fixture's pixels to 2D positions for the preview renderer.
 */
export type FixtureLayout = { fixture_id: FixtureId, 
/**
 * One position per pixel. Length must equal the fixture's pixel_count.
 */
pixel_positions: Array<Position2D>, shape: LayoutShape, };
