// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulbShape } from "./BulbShape";
import type { ChannelOrder } from "./ChannelOrder";
import type { ColorModel } from "./ColorModel";
import type { FixtureId } from "./FixtureId";
import type { PixelType } from "./PixelType";

/**
 * A fixture definition. Represents a logical light or string of lights.
 * This is purely about *what* the light is, not *how* it's connected.
 * Connection info lives in `Patch` and `Controller`.
 */
export type FixtureDef = { id: FixtureId, name: string, color_model: ColorModel, 
/**
 * Number of individually addressable pixels. 1 for simple fixtures.
 */
pixel_count: number, pixel_type: PixelType, bulb_shape: BulbShape, display_radius_override?: number | null, channel_order: ChannelOrder, };
