// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Newtype for fixture identity. Prevents mixing up fixture IDs with other integers.
 */
export type FixtureId = number;
