// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { GroupMember } from "./GroupMember";

/**
 * A named group of fixtures for targeting effects. Supports hierarchical nesting.
 */
export type FixtureGroup = { id: GroupId, name: string, members: Array<GroupMember>, };
