// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single frame of output: colors for every pixel of every fixture.
 *
 * Only fixtures with non-black pixels are included. Pixel data is
 * base64-encoded RGBA bytes for compact serialization over IPC.
 */
export type Frame = { 
/**
 * Map from fixture ID to base64-encoded RGBA pixel data.
 * Each string decodes to `pixel_count * 4` bytes (R, G, B, A per pixel).
 * Fixtures that are all-black are omitted.
 */
fixtures: { [key in number]: string }, };
