// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetEffectDetailParams = { sequence_index: number, track_index: number, effect_index: number, };
