// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed return for ListGlobalLibrary.
 */
export type GlobalLibrarySummary = { gradients: Array<string>, curves: Array<string>, scripts: Array<string>, };
