// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixtureId } from "./FixtureId";
import type { GroupId } from "./GroupId";

/**
 * A member of a group: either a direct fixture or a nested sub-group.
 */
export type GroupMember = { "Fixture": FixtureId } | { "Group": GroupId };
