// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChordEvent } from "./ChordEvent";

export type HarmonyAnalysis = { 
/**
 * Detected key (e.g., "C major", "A minor")
 */
key: string, 
/**
 * Key detection confidence (0.0 - 1.0)
 */
key_confidence: number, 
/**
 * Chord progression over time
 */
chords: Array<ChordEvent>, };
