// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HelpParams = { 
/**
 * Category name or command name to get details for (e.g. "edit", "add_effect").
 * Omit to see all categories.
 */
topic: string | null, };
