// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportVixenParams = { system_config_path: string, sequence_paths: Array<string>, };
