// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transparent newtype for `serde_json::Value` with a ts-rs override.
 * Used for `GetAnalysisDetail` which returns dynamic JSON.
 */
export type JsonValue = unknown;
