// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixtureLayout } from "./FixtureLayout";

/**
 * The spatial layout of all fixtures for preview rendering.
 */
export type Layout = { fixtures: Array<FixtureLayout>, };
