// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position2D } from "./Position2D";

/**
 * Describes the geometric shape used to distribute fixture pixels in the layout.
 */
export type LayoutShape = { "Line": { start: Position2D, end: Position2D, } } | { "Arc": { center: Position2D, radius: number, start_angle: number, end_angle: number, } } | { "Rectangle": { top_left: Position2D, bottom_right: Position2D, } } | { "Grid": { top_left: Position2D, bottom_right: Position2D, columns: number, } } | "Custom";
