// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkEffectToLibraryParams = { track_index: number, effect_index: number, key: string, ref_type: string, library_name: string, };
