// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Redacted view of the LLM config returned to the frontend (no raw API key).
 */
export type LlmConfigInfo = { has_api_key: boolean, model: string | null, };
