// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMode } from "./ChatMode";
import type { LlmProvider } from "./LlmProvider";

/**
 * Redacted view of the LLM config returned to the frontend (no raw API key).
 */
export type LlmConfigInfo = { provider: LlmProvider, has_api_key: boolean, base_url: string | null, model: string | null, chat_mode: ChatMode, };
