// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full configuration for the LLM provider (Anthropic only).
 *
 * The `api_key` field is never written to `settings.json`. It is stored in a
 * separate credentials file and loaded/saved via [`load_api_key`]/[`save_api_key`].
 */
export type LlmProviderConfig = { 
/**
 * Received over IPC but never persisted in settings.json (stored in separate credentials file).
 */
api_key?: string | null, 
/**
 * Model override. None = use provider default.
 */
model: string | null, };
