// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the motion path behaves outside its waypoint time range.
 */
export type LoopMode = "clamp" | "loop" | "ping_pong";
