// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LowLevelFeatures = { 
/**
 * RMS energy curve (one value per time step)
 */
rms: Array<number>, 
/**
 * Spectral centroid curve (Hz, one per time step)
 */
spectral_centroid: Array<number>, 
/**
 * Onset strength curve (one per time step)
 */
onset_strength: Array<number>, 
/**
 * Time step between samples in seconds
 */
time_step: number, 
/**
 * Chromagram: 12 rows (C, C#, ..., B) x N time steps, flattened row-major
 */
chromagram: Array<number>, 
/**
 * Number of time steps (columns in the chromagram)
 */
chromagram_length: number, };
