// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyricWord = { word: string, 
/**
 * Start time in seconds
 */
start: number, 
/**
 * End time in seconds
 */
end: number, 
/**
 * Confidence (0.0 - 1.0)
 */
confidence: number, };
