// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyricWord } from "./LyricWord";

export type LyricsAnalysis = { 
/**
 * Word-level timestamps
 */
words: Array<LyricWord>, 
/**
 * Full transcription text
 */
full_text: string, 
/**
 * Detected language code (e.g., "en")
 */
language: string, };
