// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoodAnalysis = { 
/**
 * Valence: negative (sad) to positive (happy), 0.0 - 1.0
 */
valence: number, 
/**
 * Arousal: calm to energetic, 0.0 - 1.0
 */
arousal: number, 
/**
 * Danceability, 0.0 - 1.0
 */
danceability: number, 
/**
 * Predicted genres with confidence scores
 */
genres: { [key in string]: number }, };
