// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopMode } from "./LoopMode";
import type { Waypoint } from "./Waypoint";

/**
 * A keyframed 2D path through layout space.
 *
 * Waypoints are sorted by time. At least one waypoint is required.
 * Evaluate at any absolute time to get the interpolated (x, y) position.
 */
export type MotionPath = { waypoints: Array<Waypoint>, loop_mode: LoopMode, };
