// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteEvent = { 
/**
 * MIDI note number (0-127)
 */
midi_note: number, 
/**
 * Start time in seconds
 */
start: number, 
/**
 * End time in seconds
 */
end: number, 
/**
 * Velocity / amplitude (0.0 - 1.0)
 */
velocity: number, };
