// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelOrder } from "./ChannelOrder";
import type { ControllerId } from "./ControllerId";
import type { DmxAddress } from "./DmxAddress";
import type { Universe } from "./Universe";

/**
 * Where a fixture's channel data is sent.
 */
export type OutputMapping = { "Dmx": { universe: Universe, start_address: DmxAddress, channel_order: ChannelOrder, } } | { "PixelPort": { controller_id: ControllerId, port: number, channel_order: ChannelOrder, } };
