// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamType } from "./ParamType";
import type { ParamValue } from "./ParamValue";

/**
 * Schema entry for one effect parameter: key, label, type constraints, and default value.
 */
export type ParamSchema = { key: string, label: string, param_type: ParamType, default: ParamValue, };
