// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { ColorGradient } from "./ColorGradient";
import type { Curve } from "./Curve";

/**
 * Type-safe parameter values for effects. Extensible without stringly-typed nonsense.
 */
export type ParamValue = { "Float": number } | { "Int": number } | { "Bool": boolean } | { "Color": Color } | { "ColorList": Array<Color> } | { "Text": string } | { "Curve": Curve } | { "ColorGradient": ColorGradient };
