// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All known effect parameter keys. Compile-time checked.
 */
export type ParamKey = "color" | "colors" | "gradient" | "movement_curve" | "pulse_curve" | "intensity_curve" | "color_mode" | "speed" | "pulse_width" | "background_level" | "reverse" | "spread" | "saturation" | "brightness" | "rate" | "duty_cycle" | "density" | "offset" | "direction" | "center_x" | "center_y" | "pass_count" | "wipe_on";
