// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes the type and constraints for an effect parameter, used to drive UI generation.
 */
export type ParamType = { "Float": { min: number, max: number, step: number, } } | { "Int": { min: number, max: number, } } | "Bool" | "Color" | { "ColorList": { min_colors: number, max_colors: number, } } | "Curve" | { "ColorGradient": { min_stops: number, max_stops: number, } } | { "Select": { options: Array<string>, } };
