// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixtureId } from "./FixtureId";
import type { OutputMapping } from "./OutputMapping";

/**
 * How a fixture's pixel data gets mapped to a physical output.
 * This is the "patch" - it connects logical fixtures to physical channels.
 * Kept as a separate concern from the fixture itself so the same fixture
 * definition can be re-patched to different controllers/universes.
 */
export type Patch = { fixture_id: FixtureId, output: OutputMapping, };
