// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a fixture uses individually-addressable (smart) or ganged (dumb) pixels.
 */
export type PixelType = "Smart" | "Dumb";
