// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybackInfo = { playing: boolean, current_time: number, duration: number, sequence_index: number, region: [number, number] | null, looping: boolean, };
