// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 2D position for preview rendering. Coordinates are normalized (0.0 to 1.0).
 */
export type Position2D = { x: number, y: number, };
