// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectParams } from "./EffectParams";

export type PreviewScriptFrameParams = { name: string, params: EffectParams, pixel_count: number, t: number, };
