// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary info for listing profiles (cheap to compute).
 */
export type ProfileSummary = { name: string, slug: string, created_at: string, sequence_count: number, fixture_count: number, };
