// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Controller } from "./Controller";
import type { FixtureDef } from "./FixtureDef";
import type { FixtureGroup } from "./FixtureGroup";
import type { Layout } from "./Layout";
import type { Patch } from "./Patch";

/**
 * Full profile data loaded into memory.
 */
export type Profile = { name: string, slug: string, fixtures: Array<FixtureDef>, groups: Array<FixtureGroup>, controllers: Array<Controller>, patches: Array<Patch>, layout: Layout, };
