// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProgressEvent = { operation: string, phase: string, progress: number, detail: string | null, };
