// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PythonEnvStatus = { uv_available: boolean, python_installed: boolean, venv_exists: boolean, deps_installed: boolean, installed_models: Array<string>, sidecar_running: boolean, sidecar_port: number, gpu_available: boolean, };
