// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptError } from "./ScriptError";
import type { ScriptParamInfo } from "./ScriptParamInfo";

export type ScriptCompileResult = { success: boolean, errors: Array<ScriptError>, name: string, params: Array<ScriptParamInfo> | null, };
