// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptError } from "./ScriptError";

export type ScriptCompileResult = { success: boolean, errors: Array<ScriptError>, name: string, };
