// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamType } from "./ParamType";
import type { ParamValue } from "./ParamValue";

export type ScriptParamInfo = { name: string, param_type: ParamType, default: ParamValue | null, };
