// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight section info for the summary.
 */
export type SectionSummary = { label: string, start: number, end: number, };
