// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorGradient } from "./ColorGradient";
import type { Curve } from "./Curve";
import type { Track } from "./Track";

/**
 * A sequence is the top-level timeline container. One sequence per song/show.
 */
export type Sequence = { name: string, 
/**
 * Duration in seconds.
 */
duration: number, 
/**
 * Target frames per second for evaluation.
 */
frame_rate: number, 
/**
 * Audio file path, if any.
 */
audio_file: string | null, 
/**
 * Tracks layered bottom (index 0) to top.
 */
tracks: Array<Track>, 
/**
 * DSL effect scripts. Key = script name, Value = source code.
 */
scripts: { [key in string]: string }, 
/**
 * Reusable color gradients. Key = library item name.
 */
gradient_library: { [key in string]: ColorGradient }, 
/**
 * Reusable curves. Key = library item name.
 */
curve_library: { [key in string]: Curve }, };
