// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotionPath } from "./MotionPath";
import type { Track } from "./Track";

/**
 * A sequence is the top-level timeline container. One sequence per song/show.
 */
export type Sequence = { name: string, 
/**
 * Duration in seconds.
 */
duration: number, 
/**
 * Target frames per second for evaluation.
 */
frame_rate: number, 
/**
 * Audio file path, if any.
 */
audio_file: string | null, 
/**
 * Tracks layered bottom (index 0) to top.
 */
tracks: Array<Track>, 
/**
 * Named motion paths. Key = path name.
 */
motion_paths: { [key in string]: MotionPath }, };
