// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary info for listing sequences.
 */
export type SequenceSummary = { name: string, slug: string, };
