// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorGradient } from "./ColorGradient";

export type SetGlobalGradientParams = { name: string, gradient: ColorGradient, };
