// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMode } from "./ChatMode";
import type { LlmProvider } from "./LlmProvider";

export type SetLlmConfigParams = { provider: LlmProvider, api_key: string, base_url: string | null, model: string | null, chat_mode: ChatMode | null, };
