// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorStop } from "./ColorStop";

export type SetLibraryGradientParams = { name: string, stops: Array<ColorStop>, };
