// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Controller } from "./Controller";
import type { FixtureDef } from "./FixtureDef";
import type { FixtureGroup } from "./FixtureGroup";
import type { Layout } from "./Layout";
import type { Patch } from "./Patch";
import type { Sequence } from "./Sequence";

/**
 * The top-level show model. Contains everything needed to describe and render a light show.
 */
export type Show = { name: string, fixtures: Array<FixtureDef>, groups: Array<FixtureGroup>, layout: Layout, sequences: Array<Sequence>, 
/**
 * Output patching: maps fixtures to physical controller outputs.
 */
patches: Array<Patch>, 
/**
 * Physical controllers in this show's setup.
 */
controllers: Array<Controller>, };
