// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StemAnalysis = { 
/**
 * Relative path to vocals stem WAV
 */
vocals: string, 
/**
 * Relative path to drums stem WAV
 */
drums: string, 
/**
 * Relative path to bass stem WAV
 */
bass: string, 
/**
 * Relative path to other/accompaniment stem WAV
 */
other: string, };
