// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A time range within a sequence. Start must be < end, both in seconds.
 * Constructed via `TimeRange::new` which enforces this invariant.
 */
export type TimeRange = { start: number, end: number, };
