// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlendMode } from "./BlendMode";
import type { EffectInstance } from "./EffectInstance";
import type { EffectTarget } from "./EffectTarget";

/**
 * A track targets a set of fixtures and contains a list of non-overlapping effect instances.
 * Tracks are layered bottom-to-top with a blend mode.
 */
export type Track = { name: string, target: EffectTarget, effects: Array<EffectInstance>, blend_mode: BlendMode, };
