// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Undo/redo state for the UI.
 */
export type UndoState = { can_undo: boolean, can_redo: boolean, undo_description: string | null, redo_description: string | null, };
