// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DMX universe number (0-indexed internally, shown as 1-indexed to users).
 */
export type Universe = number;
