// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKey } from "./ParamKey";
import type { ParamValue } from "./ParamValue";

export type UpdateEffectParamParams = { track_index: number, effect_index: number, key: ParamKey, value: ParamValue, };
