// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Controller } from "./Controller";
import type { Patch } from "./Patch";

export type UpdateSetupOutputsParams = { controllers: Array<Controller>, patches: Array<Patch>, };
