// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldUpdate } from "./FieldUpdate";

export type UpdateSequenceSettingsParams = { name: string | null, audio_file: FieldUpdate<string> | null, duration: number | null, frame_rate: number | null, };
