// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixtureDef } from "./FixtureDef";
import type { FixtureGroup } from "./FixtureGroup";

export type UpdateProfileFixturesParams = { fixtures: Array<FixtureDef>, groups: Array<FixtureGroup>, };
