// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user selected for import (sent from frontend).
 */
export type VixenImportConfig = { vixen_dir: string, setup_name: string, import_controllers: boolean, import_layout: boolean, 
/**
 * Optional user-provided path to the file containing preview/layout data.
 * When set, overrides auto-detection in `find_preview_file`.
 */
preview_file_override: string | null, sequence_paths: Array<string>, media_filenames: Array<string>, };
