// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VixenMediaInfo } from "./VixenMediaInfo";
import type { VixenSequenceInfo } from "./VixenSequenceInfo";

/**
 * Discovery result from scanning a Vixen directory.
 */
export type VixenDiscovery = { vixen_dir: string, fixtures_found: number, groups_found: number, controllers_found: number, preview_available: boolean, preview_item_count: number, 
/**
 * Path to the file containing preview data (if found).
 */
preview_file_path: string | null, sequences: Array<VixenSequenceInfo>, media_files: Array<VixenMediaInfo>, };
