// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result returned after full import.
 */
export type VixenImportResult = { setup_slug: string, fixtures_imported: number, groups_imported: number, controllers_imported: number, layout_items_imported: number, sequences_imported: number, media_imported: number, warnings: Array<string>, };
