// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Info about a discovered Vixen media file.
 */
export type VixenMediaInfo = { filename: string, path: string, size_bytes: number, };
