// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VocalSegment } from "./VocalSegment";

export type VocalPresence = { segments: Array<VocalSegment>, };
