// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EasingFunction } from "./EasingFunction";

/**
 * A single waypoint in a motion path.
 */
export type Waypoint = { 
/**
 * Absolute time in seconds within the sequence.
 */
time: number, 
/**
 * Normalized X position in layout space [0, 1].
 */
x: number, 
/**
 * Normalized Y position in layout space [0, 1].
 */
y: number, 
/**
 * Easing function for the transition FROM the previous waypoint TO this one.
 */
easing: EasingFunction, };
