// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which direction a wipe effect sweeps across fixtures.
 */
export type WipeDirection = "horizontal" | "vertical" | "diagonal_up" | "diagonal_down" | "burst" | "circle" | "diamond";
