// Auto-generated types from Rust via ts-rs.
// Do NOT edit the bindings themselves — they are regenerated by `cargo test`.
// Only edit this file to add frontend-only types or re-exports.

// ── Re-exports from generated Rust bindings ─────────────────────────

export type { AppError } from "../src-tauri/bindings/AppError";
export type { AppSettings } from "../src-tauri/bindings/AppSettings";
export type { BlendMode } from "../src-tauri/bindings/BlendMode";
export type { BulbShape } from "../src-tauri/bindings/BulbShape";
export type { ChannelOrder } from "../src-tauri/bindings/ChannelOrder";
export type { Color } from "../src-tauri/bindings/Color";
export type { ColorGradient } from "../src-tauri/bindings/ColorGradient";
export type { ColorMode } from "../src-tauri/bindings/ColorMode";
export type { ColorModel } from "../src-tauri/bindings/ColorModel";
export type { ColorStop } from "../src-tauri/bindings/ColorStop";
export type { Curve } from "../src-tauri/bindings/Curve";
export type { CurvePoint } from "../src-tauri/bindings/CurvePoint";
export type { Controller } from "../src-tauri/bindings/Controller";
export type { ControllerId } from "../src-tauri/bindings/ControllerId";
export type { ControllerProtocol } from "../src-tauri/bindings/ControllerProtocol";
export type { DmxAddress } from "../src-tauri/bindings/DmxAddress";
export type { EffectDetail } from "../src-tauri/bindings/EffectDetail";
export type { EffectInfo } from "../src-tauri/bindings/EffectInfo";
export type { EffectInstance } from "../src-tauri/bindings/EffectInstance";
export type { EffectKind } from "../src-tauri/bindings/EffectKind";
export type { EffectParams } from "../src-tauri/bindings/EffectParams";
export type { ParamValue } from "../src-tauri/bindings/ParamValue";
export type { EffectTarget } from "../src-tauri/bindings/EffectTarget";
export type { EffectThumbnail } from "../src-tauri/bindings/EffectThumbnail";
export type { FixtureDef } from "../src-tauri/bindings/FixtureDef";
export type { FixtureGroup } from "../src-tauri/bindings/FixtureGroup";
export type { FixtureId } from "../src-tauri/bindings/FixtureId";
export type { FixtureLayout } from "../src-tauri/bindings/FixtureLayout";
export type { Frame } from "../src-tauri/bindings/Frame";
export type { GroupId } from "../src-tauri/bindings/GroupId";
export type { GroupMember } from "../src-tauri/bindings/GroupMember";
export type { Layout } from "../src-tauri/bindings/Layout";
export type { LayoutShape } from "../src-tauri/bindings/LayoutShape";
export type { LlmConfigInfo } from "../src-tauri/bindings/LlmConfigInfo";
export type { LlmProviderConfig } from "../src-tauri/bindings/LlmProviderConfig";
export type { MediaFile } from "../src-tauri/bindings/MediaFile";
export type { OutputMapping } from "../src-tauri/bindings/OutputMapping";
export type { ParamKey } from "../src-tauri/bindings/ParamKey";
export type { ParamSchema } from "../src-tauri/bindings/ParamSchema";
export type { ParamType } from "../src-tauri/bindings/ParamType";
// ParamValue re-exported above alongside EffectParams
export type { Patch } from "../src-tauri/bindings/Patch";
export type { PixelType } from "../src-tauri/bindings/PixelType";
export type { PlaybackInfo } from "../src-tauri/bindings/PlaybackInfo";
export type { ProgressEvent } from "../src-tauri/bindings/ProgressEvent";
export type { Position2D } from "../src-tauri/bindings/Position2D";
export type { Setup } from "../src-tauri/bindings/Setup";
export type { SetupSummary } from "../src-tauri/bindings/SetupSummary";
export type { ScriptCompileResult } from "../src-tauri/bindings/ScriptCompileResult";
export type { ScriptError } from "../src-tauri/bindings/ScriptError";
export type { ScriptParamInfo } from "../src-tauri/bindings/ScriptParamInfo";
export type { ScriptPreviewData } from "../src-tauri/bindings/ScriptPreviewData";
export type { Sequence } from "../src-tauri/bindings/Sequence";
export type { SequenceSummary } from "../src-tauri/bindings/SequenceSummary";
export type { Show } from "../src-tauri/bindings/Show";
export type { TickResult } from "../src-tauri/bindings/TickResult";
export type { TimeRange } from "../src-tauri/bindings/TimeRange";
export type { Track } from "../src-tauri/bindings/Track";
export type { UndoState } from "../src-tauri/bindings/UndoState";
export type { Universe } from "../src-tauri/bindings/Universe";
export type { VixenDiscovery } from "../src-tauri/bindings/VixenDiscovery";
export type { VixenImportConfig } from "../src-tauri/bindings/VixenImportConfig";
export type { VixenImportResult } from "../src-tauri/bindings/VixenImportResult";
export type { VixenMediaInfo } from "../src-tauri/bindings/VixenMediaInfo";
export type { VixenSequenceInfo } from "../src-tauri/bindings/VixenSequenceInfo";
export type { EasingFunction } from "../src-tauri/bindings/EasingFunction";
export type { EffectLocation } from "../src-tauri/bindings/EffectLocation";
export type { JsonValue } from "../src-tauri/bindings/JsonValue";
export type { LoopMode } from "../src-tauri/bindings/LoopMode";
export type { MotionPath } from "../src-tauri/bindings/MotionPath";
export type { Region } from "../src-tauri/bindings/Region";
export type { Waypoint } from "../src-tauri/bindings/Waypoint";
export type { WipeDirection } from "../src-tauri/bindings/WipeDirection";

// ── Command / registry types ────────────────────────────────────────

export type { BatchAction } from "../src-tauri/bindings/BatchAction";
export type { Command } from "../src-tauri/bindings/Command";
export type { CommandCategory } from "../src-tauri/bindings/CommandCategory";
export type { CommandResult } from "../src-tauri/bindings/CommandResult";

// ── Command return types ─────────────────────────────────────────────

export type { AnalysisSummary } from "../src-tauri/bindings/AnalysisSummary";
export type { BeatsInRange } from "../src-tauri/bindings/BeatsInRange";
export type { ChatHistoryEntry } from "../src-tauri/bindings/ChatHistoryEntry";
export type { ChatRole } from "../src-tauri/bindings/ChatRole";
export type { ConversationSummary } from "../src-tauri/bindings/ConversationSummary";
export type { NewConversationResult } from "../src-tauri/bindings/NewConversationResult";
export type { SectionSummary } from "../src-tauri/bindings/SectionSummary";

// ── Command param types ─────────────────────────────────────────────

export type { AddEffectParams } from "../src-tauri/bindings/AddEffectParams";
export type { AddTrackParams } from "../src-tauri/bindings/AddTrackParams";
export type { AnalyzeAudioParams } from "../src-tauri/bindings/AnalyzeAudioParams";
export type { BatchEditParams } from "../src-tauri/bindings/BatchEditParams";
export type { CancelOperationParams } from "../src-tauri/bindings/CancelOperationParams";
export type { CheckVixenPreviewFileParams } from "../src-tauri/bindings/CheckVixenPreviewFileParams";
export type { CompileScriptPreviewParams } from "../src-tauri/bindings/CompileScriptPreviewParams";
export type { ConversationIdParams } from "../src-tauri/bindings/ConversationIdParams";
export type { CreateSequenceParams } from "../src-tauri/bindings/CreateSequenceParams";
export type { CreateSetupParams } from "../src-tauri/bindings/CreateSetupParams";
export type { DeleteEffectsParams } from "../src-tauri/bindings/DeleteEffectsParams";
export type { DeleteTrackParams } from "../src-tauri/bindings/DeleteTrackParams";
export type { GetAnalysisDetailParams } from "../src-tauri/bindings/GetAnalysisDetailParams";
export type { GetBeatsInRangeParams } from "../src-tauri/bindings/GetBeatsInRangeParams";
export type { GetEffectDetailParams } from "../src-tauri/bindings/GetEffectDetailParams";
export type { GetFrameFilteredParams } from "../src-tauri/bindings/GetFrameFilteredParams";
export type { GetFrameParams } from "../src-tauri/bindings/GetFrameParams";
export type { ImportMediaParams } from "../src-tauri/bindings/ImportMediaParams";
export type { ImportVixenParams } from "../src-tauri/bindings/ImportVixenParams";
export type { ImportVixenSequenceParams } from "../src-tauri/bindings/ImportVixenSequenceParams";
export type { ImportVixenSetupParams } from "../src-tauri/bindings/ImportVixenSetupParams";
export type { InitializeDataDirParams } from "../src-tauri/bindings/InitializeDataDirParams";
export type { MoveEffectToTrackParams } from "../src-tauri/bindings/MoveEffectToTrackParams";
export type { NameParams } from "../src-tauri/bindings/NameParams";
export type { PreviewScriptFrameParams } from "../src-tauri/bindings/PreviewScriptFrameParams";
export type { PreviewScriptParams } from "../src-tauri/bindings/PreviewScriptParams";
export type { RenameParams } from "../src-tauri/bindings/RenameParams";
export type { RenderEffectThumbnailParams } from "../src-tauri/bindings/RenderEffectThumbnailParams";
export type { ScanVixenDirectoryParams } from "../src-tauri/bindings/ScanVixenDirectoryParams";
export type { SeekParams } from "../src-tauri/bindings/SeekParams";
export type { SendAgentMessageParams } from "../src-tauri/bindings/SendAgentMessageParams";
export type { SetGlobalCurveParams } from "../src-tauri/bindings/SetGlobalCurveParams";
export type { SetGlobalGradientParams } from "../src-tauri/bindings/SetGlobalGradientParams";
export type { SetLlmConfigParams } from "../src-tauri/bindings/SetLlmConfigParams";
export type { SetLoopingParams } from "../src-tauri/bindings/SetLoopingParams";
export type { SetRegionParams } from "../src-tauri/bindings/SetRegionParams";
export type { SlugParams } from "../src-tauri/bindings/SlugParams";
export type { TickParams } from "../src-tauri/bindings/TickParams";
export type { UpdateEffectParamParams } from "../src-tauri/bindings/UpdateEffectParamParams";
export type { UpdateEffectTimeRangeParams } from "../src-tauri/bindings/UpdateEffectTimeRangeParams";
export type { UpdateSequenceSettingsParams } from "../src-tauri/bindings/UpdateSequenceSettingsParams";
export type { UpdateSetupFixturesParams } from "../src-tauri/bindings/UpdateSetupFixturesParams";
export type { UpdateSetupLayoutParams } from "../src-tauri/bindings/UpdateSetupLayoutParams";
export type { UpdateSetupOutputsParams } from "../src-tauri/bindings/UpdateSetupOutputsParams";
export type { WriteScriptParams } from "../src-tauri/bindings/WriteScriptParams";

// ── Audio analysis types ────────────────────────────────────────────

export type { AnalysisFeatures } from "../src-tauri/bindings/AnalysisFeatures";
export type { AudioAnalysis } from "../src-tauri/bindings/AudioAnalysis";
export type { BeatAnalysis } from "../src-tauri/bindings/BeatAnalysis";
export type { ChordEvent } from "../src-tauri/bindings/ChordEvent";
export type { DrumAnalysis } from "../src-tauri/bindings/DrumAnalysis";
export type { HarmonyAnalysis } from "../src-tauri/bindings/HarmonyAnalysis";
export type { LowLevelFeatures } from "../src-tauri/bindings/LowLevelFeatures";
export type { LyricWord } from "../src-tauri/bindings/LyricWord";
export type { LyricsAnalysis } from "../src-tauri/bindings/LyricsAnalysis";
export type { MoodAnalysis } from "../src-tauri/bindings/MoodAnalysis";
export type { NoteEvent } from "../src-tauri/bindings/NoteEvent";
export type { PitchAnalysis } from "../src-tauri/bindings/PitchAnalysis";
export type { PythonEnvStatus } from "../src-tauri/bindings/PythonEnvStatus";
export type { SongSection } from "../src-tauri/bindings/SongSection";
export type { StemAnalysis } from "../src-tauri/bindings/StemAnalysis";
export type { StructureAnalysis } from "../src-tauri/bindings/StructureAnalysis";
export type { VocalPresence } from "../src-tauri/bindings/VocalPresence";
export type { VocalSegment } from "../src-tauri/bindings/VocalSegment";

// ── Frontend-only types ─────────────────────────────────────────────

import type { BulbShape } from "../src-tauri/bindings/BulbShape";
import type { ParamValue } from "../src-tauri/bindings/ParamValue";

export const BULB_SHAPE_RADIUS: Record<BulbShape, number> = {
  Mini: 0.8,
  LED: 1.0,
  Icicle: 1.2,
  C7: 1.5,
  Globe: 1.8,
  C9: 2.0,
  Snowflake: 2.5,
  Flood: 3.0,
};

export type InteractionMode = "select" | "edit" | "swipe";

/** Simple string-keyed param map for script params (all Custom keys). */
export type ScriptParams = Record<string, ParamValue>;

// ── Type helpers for serde enum unions ────────────────────────────
// ParamKey and EffectKind include object variants ({ Custom: string }, { Script: string })
// from Rust's serde. These helpers extract a plain string for use as keys, labels, etc.

import type { ParamKey } from "../src-tauri/bindings/ParamKey";
import type { EffectKind } from "../src-tauri/bindings/EffectKind";

export function paramKeyStr(key: ParamKey): string {
  return typeof key === "string" ? key : key.Custom;
}

export function effectKindLabel(kind: EffectKind): string {
  return typeof kind === "string" ? kind : kind.Script;
}
