// Auto-generated types from Rust via ts-rs.
// Do NOT edit the bindings themselves — they are regenerated by `cargo test`.
// Only edit this file to add frontend-only types or re-exports.

// ── Re-exports from generated Rust bindings ─────────────────────────

export type { AppError } from "../src-tauri/bindings/AppError";
export type { AppSettings } from "../src-tauri/bindings/AppSettings";
export type { BlendMode } from "../src-tauri/bindings/BlendMode";
export type { BulbShape } from "../src-tauri/bindings/BulbShape";
export type { ChannelOrder } from "../src-tauri/bindings/ChannelOrder";
export type { Color } from "../src-tauri/bindings/Color";
export type { ColorGradient } from "../src-tauri/bindings/ColorGradient";
export type { ColorMode } from "../src-tauri/bindings/ColorMode";
export type { ColorModel } from "../src-tauri/bindings/ColorModel";
export type { ColorStop } from "../src-tauri/bindings/ColorStop";
export type { Curve } from "../src-tauri/bindings/Curve";
export type { CurvePoint } from "../src-tauri/bindings/CurvePoint";
export type { Controller } from "../src-tauri/bindings/Controller";
export type { ControllerId } from "../src-tauri/bindings/ControllerId";
export type { ControllerProtocol } from "../src-tauri/bindings/ControllerProtocol";
export type { DmxAddress } from "../src-tauri/bindings/DmxAddress";
export type { EffectDetail } from "../src-tauri/bindings/EffectDetail";
export type { EffectInfo } from "../src-tauri/bindings/EffectInfo";
export type { EffectInstance } from "../src-tauri/bindings/EffectInstance";
export type { EffectKind } from "../src-tauri/bindings/EffectKind";
export type { EffectParams } from "../src-tauri/bindings/EffectParams";
export type { EffectTarget } from "../src-tauri/bindings/EffectTarget";
export type { EffectThumbnail } from "../src-tauri/bindings/EffectThumbnail";
export type { FixtureDef } from "../src-tauri/bindings/FixtureDef";
export type { FixtureGroup } from "../src-tauri/bindings/FixtureGroup";
export type { FixtureId } from "../src-tauri/bindings/FixtureId";
export type { FixtureLayout } from "../src-tauri/bindings/FixtureLayout";
export type { Frame } from "../src-tauri/bindings/Frame";
export type { GroupId } from "../src-tauri/bindings/GroupId";
export type { GroupMember } from "../src-tauri/bindings/GroupMember";
export type { Layout } from "../src-tauri/bindings/Layout";
export type { LayoutShape } from "../src-tauri/bindings/LayoutShape";
export type { MediaFile } from "../src-tauri/bindings/MediaFile";
export type { OutputMapping } from "../src-tauri/bindings/OutputMapping";
export type { ParamKey } from "../src-tauri/bindings/ParamKey";
export type { ParamSchema } from "../src-tauri/bindings/ParamSchema";
export type { ParamType } from "../src-tauri/bindings/ParamType";
export type { ParamValue } from "../src-tauri/bindings/ParamValue";
export type { Patch } from "../src-tauri/bindings/Patch";
export type { PixelType } from "../src-tauri/bindings/PixelType";
export type { PlaybackInfo } from "../src-tauri/bindings/PlaybackInfo";
export type { ProgressEvent } from "../src-tauri/bindings/ProgressEvent";
export type { Position2D } from "../src-tauri/bindings/Position2D";
export type { Profile } from "../src-tauri/bindings/Profile";
export type { ProfileSummary } from "../src-tauri/bindings/ProfileSummary";
export type { ScriptCompileResult } from "../src-tauri/bindings/ScriptCompileResult";
export type { ScriptError } from "../src-tauri/bindings/ScriptError";
export type { Sequence } from "../src-tauri/bindings/Sequence";
export type { SequenceSummary } from "../src-tauri/bindings/SequenceSummary";
export type { Show } from "../src-tauri/bindings/Show";
export type { TickResult } from "../src-tauri/bindings/TickResult";
export type { TimeRange } from "../src-tauri/bindings/TimeRange";
export type { Track } from "../src-tauri/bindings/Track";
export type { UndoState } from "../src-tauri/bindings/UndoState";
export type { Universe } from "../src-tauri/bindings/Universe";
export type { VixenDiscovery } from "../src-tauri/bindings/VixenDiscovery";
export type { VixenImportConfig } from "../src-tauri/bindings/VixenImportConfig";
export type { VixenImportResult } from "../src-tauri/bindings/VixenImportResult";
export type { VixenMediaInfo } from "../src-tauri/bindings/VixenMediaInfo";
export type { VixenSequenceInfo } from "../src-tauri/bindings/VixenSequenceInfo";
export type { WipeDirection } from "../src-tauri/bindings/WipeDirection";

// ── Audio analysis types ────────────────────────────────────────────

export type { AnalysisFeatures } from "../src-tauri/bindings/AnalysisFeatures";
export type { AudioAnalysis } from "../src-tauri/bindings/AudioAnalysis";
export type { BeatAnalysis } from "../src-tauri/bindings/BeatAnalysis";
export type { ChordEvent } from "../src-tauri/bindings/ChordEvent";
export type { DrumAnalysis } from "../src-tauri/bindings/DrumAnalysis";
export type { HarmonyAnalysis } from "../src-tauri/bindings/HarmonyAnalysis";
export type { LowLevelFeatures } from "../src-tauri/bindings/LowLevelFeatures";
export type { LyricWord } from "../src-tauri/bindings/LyricWord";
export type { LyricsAnalysis } from "../src-tauri/bindings/LyricsAnalysis";
export type { MoodAnalysis } from "../src-tauri/bindings/MoodAnalysis";
export type { NoteEvent } from "../src-tauri/bindings/NoteEvent";
export type { PitchAnalysis } from "../src-tauri/bindings/PitchAnalysis";
export type { PythonEnvStatus } from "../src-tauri/bindings/PythonEnvStatus";
export type { SongSection } from "../src-tauri/bindings/SongSection";
export type { StemAnalysis } from "../src-tauri/bindings/StemAnalysis";
export type { StructureAnalysis } from "../src-tauri/bindings/StructureAnalysis";
export type { VocalPresence } from "../src-tauri/bindings/VocalPresence";
export type { VocalSegment } from "../src-tauri/bindings/VocalSegment";

// ── Frontend-only types ─────────────────────────────────────────────

import type { BulbShape } from "../src-tauri/bindings/BulbShape";

export const BULB_SHAPE_RADIUS: Record<BulbShape, number> = {
  Mini: 0.8,
  LED: 1.0,
  Icicle: 1.2,
  C7: 1.5,
  Globe: 1.8,
  C9: 2.0,
  Snowflake: 2.5,
  Flood: 3.0,
};

export type InteractionMode = "select" | "edit" | "swipe";
